/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionEnquiry {
  'id' : string,
  'studentName' : string,
  'admissionClass' : string,
  'submittedAt' : bigint,
  'fatherName' : string,
  'village' : string,
  'phone' : string,
}
export interface Student {
  'id' : string,
  'age' : bigint,
  'parentContact' : string,
  'classSection' : string,
  'name' : string,
  'grade' : bigint,
  'enrollmentDate' : bigint,
}
export type Subject = { 'LanguageArts' : null } |
  { 'ComputerScience' : null } |
  { 'Mathematics' : null } |
  { 'PhysicalEducation' : null } |
  { 'Music' : null } |
  { 'Science' : null };
export interface Teacher {
  'id' : string,
  'bio' : string,
  'yearsOfExperience' : bigint,
  'subject' : Subject,
  'name' : string,
  'email' : string,
  'phone' : string,
  'profileImageUrl' : string,
}
export interface _SERVICE {
  'getAdmissionEnquiries' : ActorMethod<[], Array<AdmissionEnquiry>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllTeachers' : ActorMethod<[], Array<Teacher>>,
  'getStudentById' : ActorMethod<[string], Student>,
  'getTeacherById' : ActorMethod<[string], Teacher>,
  'seedData' : ActorMethod<[], undefined>,
  'submitAdmissionEnquiry' : ActorMethod<
    [string, string, string, string, string],
    AdmissionEnquiry
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];