/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TeacherResource = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'externalLink' : IDL.Text,
  'fileData' : IDL.Text,
  'description' : IDL.Text,
  'fileName' : IDL.Text,
  'resourceType' : IDL.Text,
  'category' : IDL.Text,
  'uploadedAt' : IDL.Int,
  'textContent' : IDL.Text,
});
export const AdmissionEnquiry = IDL.Record({
  'id' : IDL.Text,
  'studentName' : IDL.Text,
  'admissionClass' : IDL.Text,
  'submittedAt' : IDL.Int,
  'fatherName' : IDL.Text,
  'village' : IDL.Text,
  'phone' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'parentContact' : IDL.Text,
  'classSection' : IDL.Text,
  'name' : IDL.Text,
  'grade' : IDL.Nat,
  'enrollmentDate' : IDL.Int,
});
export const Subject = IDL.Variant({
  'LanguageArts' : IDL.Null,
  'ComputerScience' : IDL.Null,
  'Mathematics' : IDL.Null,
  'PhysicalEducation' : IDL.Null,
  'Music' : IDL.Null,
  'Science' : IDL.Null,
});
export const Teacher = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'yearsOfExperience' : IDL.Nat,
  'subject' : Subject,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'profileImageUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'addTeacherResource' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [TeacherResource],
      [],
    ),
  'deleteTeacherResource' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAdmissionEnquiries' : IDL.Func(
      [],
      [IDL.Vec(AdmissionEnquiry)],
      ['query'],
    ),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllTeacherResources' : IDL.Func(
      [],
      [IDL.Vec(TeacherResource)],
      ['query'],
    ),
  'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'getStudentById' : IDL.Func([IDL.Text], [Student], ['query']),
  'getTeacherById' : IDL.Func([IDL.Text], [Teacher], ['query']),
  'seedData' : IDL.Func([], [], []),
  'submitAdmissionEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [AdmissionEnquiry],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TeacherResource = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'externalLink' : IDL.Text,
    'fileData' : IDL.Text,
    'description' : IDL.Text,
    'fileName' : IDL.Text,
    'resourceType' : IDL.Text,
    'category' : IDL.Text,
    'uploadedAt' : IDL.Int,
    'textContent' : IDL.Text,
  });
  const AdmissionEnquiry = IDL.Record({
    'id' : IDL.Text,
    'studentName' : IDL.Text,
    'admissionClass' : IDL.Text,
    'submittedAt' : IDL.Int,
    'fatherName' : IDL.Text,
    'village' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'parentContact' : IDL.Text,
    'classSection' : IDL.Text,
    'name' : IDL.Text,
    'grade' : IDL.Nat,
    'enrollmentDate' : IDL.Int,
  });
  const Subject = IDL.Variant({
    'LanguageArts' : IDL.Null,
    'ComputerScience' : IDL.Null,
    'Mathematics' : IDL.Null,
    'PhysicalEducation' : IDL.Null,
    'Music' : IDL.Null,
    'Science' : IDL.Null,
  });
  const Teacher = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'yearsOfExperience' : IDL.Nat,
    'subject' : Subject,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'profileImageUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'addTeacherResource' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [TeacherResource],
        [],
      ),
    'deleteTeacherResource' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAdmissionEnquiries' : IDL.Func(
        [],
        [IDL.Vec(AdmissionEnquiry)],
        ['query'],
      ),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllTeacherResources' : IDL.Func(
        [],
        [IDL.Vec(TeacherResource)],
        ['query'],
      ),
    'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'getStudentById' : IDL.Func([IDL.Text], [Student], ['query']),
    'getTeacherById' : IDL.Func([IDL.Text], [Teacher], ['query']),
    'seedData' : IDL.Func([], [], []),
    'submitAdmissionEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [AdmissionEnquiry],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };