/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AdmissionEnquiry {
    id: string;
    studentName: string;
    admissionClass: string;
    submittedAt: bigint;
    fatherName: string;
    village: string;
    phone: string;
}
export interface TeacherResource {
    id: string;
    title: string;
    externalLink: string;
    fileData: string;
    description: string;
    fileName: string;
    resourceType: string;
    category: string;
    uploadedAt: bigint;
    textContent: string;
}
export interface Teacher {
    id: string;
    bio: string;
    yearsOfExperience: bigint;
    subject: Subject;
    name: string;
    email: string;
    phone: string;
    profileImageUrl: string;
}
export interface Student {
    id: string;
    age: bigint;
    parentContact: string;
    classSection: string;
    name: string;
    grade: bigint;
    enrollmentDate: bigint;
}
export enum Subject {
    LanguageArts = "LanguageArts",
    ComputerScience = "ComputerScience",
    Mathematics = "Mathematics",
    PhysicalEducation = "PhysicalEducation",
    Music = "Music",
    Science = "Science"
}
export interface backendInterface {
    addTeacherResource(title: string, description: string, resourceType: string, fileData: string, fileName: string, externalLink: string, textContent: string, category: string): Promise<TeacherResource>;
    deleteTeacherResource(id: string): Promise<boolean>;
    getAdmissionEnquiries(): Promise<Array<AdmissionEnquiry>>;
    getAllStudents(): Promise<Array<Student>>;
    getAllTeacherResources(): Promise<Array<TeacherResource>>;
    getAllTeachers(): Promise<Array<Teacher>>;
    getStudentById(id: string): Promise<Student>;
    getTeacherById(id: string): Promise<Teacher>;
    seedData(): Promise<void>;
    submitAdmissionEnquiry(studentName: string, fatherName: string, village: string, admissionClass: string, phone: string): Promise<AdmissionEnquiry>;
    uploadDatesheet(data: string, name: string): Promise<boolean>;
    getDatesheet(): Promise<[string, string]>;
    addLike(): Promise<bigint>;
    getLikeCount(): Promise<bigint>;
}
import type { Subject as _Subject, Teacher as _Teacher } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTeacherResource(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<TeacherResource> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeacherResource(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeacherResource(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async deleteTeacherResource(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeacherResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeacherResource(arg0);
            return result;
        }
    }
    async getAdmissionEnquiries(): Promise<Array<AdmissionEnquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdmissionEnquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdmissionEnquiries();
            return result;
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return result;
        }
    }
    async getAllTeacherResources(): Promise<Array<TeacherResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeacherResources();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeacherResources();
            return result;
        }
    }
    async getAllTeachers(): Promise<Array<Teacher>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeachers();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeachers();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentById(arg0: string): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentById(arg0);
            return result;
        }
    }
    async getTeacherById(arg0: string): Promise<Teacher> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherById(arg0);
                return from_candid_Teacher_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherById(arg0);
            return from_candid_Teacher_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async submitAdmissionEnquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<AdmissionEnquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAdmissionEnquiry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAdmissionEnquiry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async uploadDatesheet(data: string, name: string): Promise<boolean> {
        const result = await this.actor.uploadDatesheet(data, name);
        return result;
    }
    async getDatesheet(): Promise<[string, string]> {
        const result = await this.actor.getDatesheet();
        return result as [string, string];
    }
    async addLike(): Promise<bigint> {
        const result = await this.actor.addLike();
        return result as bigint;
    }
    async getLikeCount(): Promise<bigint> {
        const result = await this.actor.getLikeCount();
        return result as bigint;
    }
}
function from_candid_Subject_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Teacher_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Teacher): Teacher {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    yearsOfExperience: bigint;
    subject: _Subject;
    name: string;
    email: string;
    phone: string;
    profileImageUrl: string;
}): {
    id: string;
    bio: string;
    yearsOfExperience: bigint;
    subject: Subject;
    name: string;
    email: string;
    phone: string;
    profileImageUrl: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        yearsOfExperience: value.yearsOfExperience,
        subject: from_candid_Subject_n4(_uploadFile, _downloadFile, value.subject),
        name: value.name,
        email: value.email,
        phone: value.phone,
        profileImageUrl: value.profileImageUrl
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    LanguageArts: null;
} | {
    ComputerScience: null;
} | {
    Mathematics: null;
} | {
    PhysicalEducation: null;
} | {
    Music: null;
} | {
    Science: null;
}): Subject {
    return "LanguageArts" in value ? Subject.LanguageArts : "ComputerScience" in value ? Subject.ComputerScience : "Mathematics" in value ? Subject.Mathematics : "PhysicalEducation" in value ? Subject.PhysicalEducation : "Music" in value ? Subject.Music : "Science" in value ? Subject.Science : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Teacher>): Array<Teacher> {
    return value.map((x)=>from_candid_Teacher_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
